export const siteConfig = {
  branding: {
    name: "EXINX",
    fullName: "Extended Intelligence",
    tagline: "Where Intelligence Meets Imagination",
  },
  colors: {
    bg: "#0a0a0f",
    bgWarm: "#0d0c14",
    surface: "#141420",
    surfaceLight: "#1c1c2e",
    accent: "#f0a030",
    accentGlow: "rgba(240, 160, 48, 0.25)",
    accentSecondary: "#e06040",
    nova: "#60d0f0",
    orbis: "#a070f0",
    astra: "#f07050",
    text: "#f0ede6",
    textMuted: "#8a8698",
    textDim: "#5a5668",
  },
  nav: {
    links: [
      { label: "Nova", href: "/nova" },
      { label: "Orbis", href: "/orbis" },
      { label: "Astra", href: "/astra" },
    ],
    cta: "Signal Us",
  },
  hero: {
    badge: "AI x EdTech",
    title: {
      line1: "The Future of",
      line2: "Learning is",
      line3: "Already Here.",
    },
    description: "EXINX builds AI-native educational products that don't just teach — they think with you. Three tools. One mission. Infinite potential. Welcome to the platform that adapts to how your mind actually works.",
    actions: {
      primary: "Explore Products →",
      secondary: "Learn More",
    },
    stats: [
      { value: "12K+", label: "Waitlist Signups", target: 12 },
      { value: "3", label: "AI Products", target: 3 },
      { value: "98%", label: "Learning Retention", target: 98 },
    ],
  },
  marquee: [
    "Adaptive Learning",
    "Neural Pathways",
    "Knowledge Graphs",
    "Smart Assessment",
    "Collaborative AI",
    "Deep Understanding",
    "Real-Time Analytics",
    "Infinite Curiosity",
  ],
  about: {
    label: "Our Philosophy",
    title: "Education shouldn't be one-size-fits-all. It should be one-size-fits-you.",
    description1: "EXINX was born from a frustration: despite billions spent on edtech, most platforms still deliver static content wrapped in gamification. We asked a different question — what if the AI didn't just deliver content, but truly understood how you learn?",
    description2: "Our founding team of AI researchers, cognitive scientists, and educators spent two years building the neural architecture that powers Nova, Orbis, and Astra. Not chatbots with education prompts — purpose-built intelligence designed from the ground up for learning.",
    description3: "The result? Three products that work independently yet amplify each other. A learning companion that knows you. A knowledge platform that connects minds. An assessment engine that measures what matters. Together, they form the most intelligent education ecosystem ever built.",
    philosophy: [
      {
        num: "01",
        title: "Adaptive Intelligence",
        text: "Our AI doesn't follow a script. It reads your learning patterns, identifies gaps, and builds a path that's uniquely yours.",
      },
      {
        num: "02",
        title: "Depth Over Speed",
        text: "We optimize for true understanding, not completion badges. When you learn with EXINX, you actually retain it.",
      },
      {
        num: "03",
        title: "Human + Machine",
        text: "AI handles the structure. You bring the curiosity. Together, we create learning experiences that feel alive.",
      },
      {
        num: "04",
        title: "Privacy First",
        text: "Your learning data belongs to you. We process, adapt, and personalize — without ever selling or sharing your information.",
      },
    ],
  },
  products: {
    label: "Three Products. One Vision.",
    title: "Meet the EXINX Ecosystem",
    subtitle: "Each product is powerful alone. Together, they transform how humanity learns.",
    items: [
      {
        id: "nova",
        tag: "AI Learning Companion",
        name: "Nova",
        subtitle: "Your personal AI that learns how you learn.",
        description: "Nova is not a tutor. It's a thinking partner. It studies your cognitive patterns, identifies where your understanding breaks down, and reconstructs explanations in ways that click for your specific brain.",
        features: [
          "Adapts explanations in real-time",
          "Socratic dialogue mode",
          "Multi-modal responses",
          "Remembers your journey",
          "Supports 40+ academic subjects",
        ],
        cta: "Try Nova",
        color: "#60d0f0",
      },
      {
        id: "orbis",
        tag: "Collaborative Knowledge Platform",
        name: "Orbis",
        subtitle: "Where knowledge connects and belongs to everyone.",
        description: "Orbis transforms isolated studying into connected discovery. It builds dynamic knowledge graphs from your notes and connects you with learners exploring the same intellectual terrain.",
        features: [
          "AI-generated knowledge maps",
          "Smart study groups",
          "Cross-subject connection engine",
          "Collaborative whiteboards",
          "Community-curated paths",
        ],
        cta: "Explore Orbis",
        color: "#a070f0",
      },
      {
        id: "astra",
        tag: "AI Assessment & Analytics",
        name: "Astra",
        subtitle: "Testing that measures understanding, not memorization.",
        description: "Astra reimagines assessment. Instead of multiple-choice traps, it generates adaptive challenges that probe the depth of your understanding with real-time analytics.",
        features: [
          "Adaptive difficulty",
          "Concept-level diagnostics",
          "Predictive analytics (94% accuracy)",
          "Spaced repetition engine",
          "Teacher dashboard",
        ],
        cta: "Discover Astra",
        color: "#f07050",
      },
    ],
  },
  how: {
    label: "How It Works",
    title: "From Curious to Capable in Four Steps",
    description: "No lengthy onboarding. No boring tutorials. Just you, your curiosity, and AI that gets it.",
    steps: [
      {
        num: "01",
        icon: "🎯",
        title: "Tell Us Your Goal",
        text: "Preparing for an exam? Exploring a new field? Sharing what you want to learn — Nova listens.",
      },
      {
        num: "02",
        icon: "🧠",
        title: "AI Maps Your Mind",
        text: "Through a conversational assessment, Astra identifies your knowledge level and optimal challenge zone.",
      },
      {
        num: "03",
        icon: "⚡",
        title: "Learn, Connect, Grow",
        text: "Nova teaches, Orbis connects you with peers, and Astra continuously refines your understanding.",
      },
      {
        num: "04",
        icon: "🚀",
        title: "Master Anything",
        text: "Watch your knowledge graph expand and your confidence soar. The EXINX ecosystem grows with you.",
      },
    ],
  },
  testimonials: {
    label: "Early Access Stories",
    title: "Lives Already Changing",
    items: [
      {
        quote: "I've tried every edtech app on the market. Nova is the first one that actually feels like it understands me. It explained quantum mechanics in a way that finally made sense.",
        author: "Sarah Rodriguez",
        role: "Physics Student, MIT",
        initials: "SR",
        color: "nova",
      },
      {
        quote: "Orbis changed how our entire study group learns. The knowledge graphs it builds are insane — we discovered connections between chemistry and music theory we never would have found.",
        author: "James Kimathi",
        role: "Medical Student, Stanford",
        initials: "JK",
        color: "orbis",
      },
      {
        quote: "As a teacher, Astra has been revelatory. I can finally see exactly where each student's understanding breaks down. My class average went up 23% in one semester.",
        author: "Dr. Maya Patel",
        role: "High School Principal, Chicago",
        initials: "MP",
        color: "astra",
      },
    ],
  },
  cta: {
    label: "The Wait Is Almost Over",
    title: "Ready to learn the way your mind was built to?",
    description: "Join 12,000+ curious minds on the EXINX waitlist. Early access members get lifetime benefits and locked-in pricing forever.",
    primary: "Join the Waitlist — It's Free →",
    secondary: "See Products First",
    note: "No credit card required · Early access pricing locked forever · Cancel anytime",
  },
  footer: {
    description: "Building the intelligence layer for human learning. Nova, Orbis and Astra. One mission. Infinite potential for every mind on Earth.",
    columns: [
      {
        title: "Products",
        links: [
          { label: "Nova — AI Companion", href: "/nova" },
          { label: "Orbis — Knowledge Platform", href: "/orbis" },
          { label: "Astra — Smart Assessment", href: "/astra" },
          { label: "Pricing", href: "#" },
        ],
      },
      {
        title: "Company",
        links: [
          { label: "About Us", href: "#" },
          { label: "Careers", href: "#" },
          { label: "Blog", href: "#" },
          { label: "Contact", href: "#" },
        ],
      },
      {
        title: "Resources",
        links: [
          { label: "Documentation", href: "#" },
          { label: "API Reference", href: "#" },
          { label: "Privacy Policy", href: "#" },
          { label: "Terms", href: "#" },
        ],
      },
    ],
    copyright: "© 2025 EXINX Technologies. All rights reserved.",
  },
};
